[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
aptPkgs = [
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "libgomp1"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
